// global css loaded for every page
import './globals.css'
// font
import { Inter } from 'next/font/google'

// components
import Navbar from './components/Navbar'
// applying font to body tag
const inter = Inter({ subsets: ['latin'] })

// this is how we make meta data for a next apps
// will be used for every page, can override with a page by page basis
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
// layout components wrap page components
// this prop are compoennts
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <nav>
          <h1>Dojo Helpdesk</h1>
          <Link href="/">Dashboard</Link>
          <Link href="/tickets">Tickets</Link>
        </nav> */}
        <Navbar />
        {children}
      </body>
    </html>
  )
}
