import './globals.css'
// import from google fonts
import { Rubik } from 'next/font/google'

// components
import Navbar from './components/Navbar'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* apply custom fonts to the template */}
      
      <body className={rubik.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
